version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2602Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_2602.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GIT_2602Project
    version: "1.0"
- serviceName: project.siqa_git_2602.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GIT_2602Project
    version: "1.0"
